name: Test on FreeBSD
on: [push, pull_request]

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Test with FreeBSD Linux compatibility
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            echo 'FreeBSD-ports: { url: "pkg+https://pkg.FreeBSD.org/${ABI}/latest", mirror_type: "srv", signature_type: "fingerprints", fingerprints: "/usr/share/keys/pkg", enabled: yes }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            kldload linux64.ko
            pkg update
            pkg install -y curl bash babashka
          run: |
            # Enable Linux compatibility layer
            sysrc linux_enable="YES"
            service linux start

            bb --version
            bb -e "(println \"Hello from FreeBSD!\")"
            bb -e '(fs/list-dir ".")'
            realpath .
            bb -e '(fs/real-path ".")'
            bb -e '(spit "foo.txt" "hello")'
            bb -e '(fs/list-dir ".")'
            time bb -e ':ok'
            time bb -e ':ok'
            time bb -e ':ok'
