name: Test on FreeBSD
on: [push, pull_request]

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Test with FreeBSD Linux compatibility
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y curl bash
          run: |
            # Enable Linux compatibility layer
            sysrc linux_enable="YES"
            service linux start

            # Download static Linux binary
            curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
            chmod +x ./install
            ./install

            bb --version
            bb -e "(println \"Hello from FreeBSD!\")"
            bb -e '(fs/list-dir ".")'
            realpath .
            bb -e '(fs/real-path ".")'
            bb -e '(spit "foo.txt" "hello")'
            bb -e '(fs/list-dir ".")'
            time bb -e ':ok'
            time bb -e ':ok'
            time bb -e ':ok'
